# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x
#' @param y
#' @export
add_cpp2 <- function(x, y) {
    .Call(`_pkgrcpp_add_cpp2`, x, y)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_pkgrcpp_RcppExport_registerCCallable', PACKAGE = 'pkgrcpp')
})
